### ISSUE TITLE
File a bug for the CentOS 8 kickstart not finding installation media.

### ISSUE THREAD

**Issue by dafydd2277** [dafydd2277/systemAdmin#1]
Text of the bug:

Summary:
Kickstart installation requires network repositories to find USB installation source.

Description of Problem:
After adding a kickstart file to an ISO, burning that ISO to a USB flash drive, and booting from that flash drive, the installer will not find the "Installation Source" on the USB drive unless the kickstart file has several network `repo` entries added.

Version Release number of selected component (if applicable):
CentOS-8.3.2011-x86_64-dvd1.iso and whatever installer version is included in that ISO.

How reproducable:
Every time.

Steps to reproduce:
1. Use the ISO build script and kickstart file found at https://github.com/dafydd2277/systemAdmin/tree/main/kickstart/centos8
2. Boot from the resulting USB flash drive.
3. Note that the INSTALLATION SOURCE page of the INSTALLATION SUMMARY does not show an auto-detected installation media.

Actual Results:
The installer fails to find the installation media on the USB flash drive.

Expected results:
If `cdrom` is specified in the kickstart file, the installer should find the installation media on the boot device in all cases, with no other dependencies.

Additional info:
For context, this process started when I got tired of the tedium of creating a custom filesystem layout for my systems. I'm fine with using the graphical installer to do installations; I just want to preload my preferred filesystem layout. And if I was going to use a kickstart file, I'll go to the extra effort to pre-configure the timezone, root password, create an admin user, etc. I didn't want to preconfigure the network settings because those would be different for each host. I just wanted to preconfigure the settings that would be common to every installation, and use the graphical installer for the system-specific items. Similarly, I didn't care about adding external repositories because the first thing I do once I have a system up and running is a `dnf update`, so I can watch the update go by.

Aside from the github link above, here are a couple more points where I managed to clear some hurdles to getting a kickstart file onto a CentOS 8 ISO.
- https://unix.stackexchange.com/questions/640232/verified-good-mkisofs-for-centos-8
- https://unix.stackexchange.com/questions/641277/centos-8-custom-iso-adding-ks-cdrom-ks-cfg-hangs-the-install

**Comment by dafydd2277** [comment]
First comment:

Results of booting into the installer of an unmodified ISO:

LANGUAGE -> INSTALLATION SUMMARY -> INSTALLATION SOURCE
Which installation source would you like to use?
Device: sdb
Label: <blank>

**Comment by dafydd2277** [comment]
Second comment in the bug:

SETUP:
Set these commands in the kickstart file:
cdrom
network --device=link --activate --onboot=yes --bootproto=dhcp --noipv6
repo --name=AppStream --baseurl=file:///run/media/repo/AppStream

RESULT:
Forced into the Network Configuration page of the installer before reaching the summary. No installation source found.

**Comment by dafydd2277** [comment]
Third comment in the bug:

SETUP:
Set these commands in the kickstart file:
cdrom
network --device=link --activate --onboot=yes --bootproto=dhcp --noipv6
repo --name="appstream" --mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=AppStream&infra=$infra
repo --name="baseos" --mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=BaseOS&infra=$infra
repo --name="EPEL" --metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch&infra=$infra&content=$contentdir

RESULT:
Local Installation Source found, and no network configuration forced.

**Comment by dafydd2277** [comment]
Fourth comment in the bug:

SETUP:
Set these commands in the kickstart file:
cdrom
network --device=link --activate --onboot=yes --bootproto=dhcp --noipv6
repo --name="appstream" --mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=AppStream&infra=$infra
repo --name="baseos" --mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=BaseOS&infra=$infra

RESULT:
Local Installation Source found, and no network configuration forced.

**Comment by dafydd2277** [comment]
The installer has the local AppStream URL as `file:///run/installl/sources/mount-0000-cdrom/AppStream`.  However, /run/install/sources/mount-0000-cdrom/ is empty. AppStream can be found in `/run/install/repo/AppStream`.

**Comment by dafydd2277** [comment]
The installer has the local AppStream URL as file:///run/installl/sources/mount-0000-cdrom/AppStream. However, `/run/install/sources/mount-0000-cdrom/ is empty`. AppStream can be found in /run/install/repo/AppStream.

**Comment by dafydd2277** [comment]
The installer has the local AppStream URL as `file:///run/install/sources/mount-0000-cdrom/AppStream`. However, `/run/install/sources/mount-0000-cdrom/` is empty. AppStream can be found in `/run/install/repo/AppStream`.

**Comment by dafydd2277** [comment]
And experimenting with changing the local sources by hand appears to have hung the installer. This most recent test got me the local AppStream repository with the bad `file://` URL, and the remote AppStream from the kickstart file. (The test isn't in a comment here, yet. It will be the "fifth" comment in the Red Hat bug.)

I've taken a side trip in experimenting with how to change those. The installer has greyed out the option to change the local AppStream URL to one that would actually find the repodata. I'm waiting to see if the installer will un-hang so I can try setting up an "additional" repo going to the correct path. (I don't think I can. I don't think I have the option for `file://` URLs in the graphical installer.

Oh, and hey! As I'm writing this I get "An unknown error has occurred." Looking at the traceback suggests the problem was finding AppStream package @groups in the kickstart file, and no source to download from. I'll play more when I run the next kickstart/ISO test.

**Comment by dafydd2277** [comment]
Fifth comment in the bug:

SETUP:
Set these commands in the kickstart file:
cdrom
network --device=link --activate --onboot=yes --bootproto=dhcp --noipv6
repo --name="appstream" --mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=AppStream&infra=$infra

RESULT:
Local Installation Source found, and no network configuration forced. (In addition to the netowrk AppStream "Additional Resource," the installer put a local AppStream repo in Installation Source with a `file://` URL referencing an empty directory.)

NEXT TEST: No additional `repo` commands at all. (After that, I might try an AppStream repo with the good local directory again. I never formally documented the result of that test.)

**Comment by dafydd2277** [comment]
Sixth Test:

SETUP:
Set these commands in the kickstart file:
cdrom
network --device=link --activate --onboot=yes --bootproto=dhcp --noipv6

RESULT:
Local Installation Source found, and no network configuration forced. The local AppStream repository still pointed its `file://` URL at an empty directory.

**Comment by dafydd2277** [comment]
Seventh Test:

SETUP:
Set these commands in the kickstart file:
cdrom
repo --name=AppStream --baseurl=file:///run/media/repo/AppStream

RESULT:
Local Installation Source NOT found, and no network configuration forced. The local AppStream repository still pointed its `file://` URL at the specified directory.

**Comment by dafydd2277** [comment]
Eighth test:

SETUP:
cdrom
network --device=link --no-activate --onboot=no --bootproto=dhcp --noipv6
repo --name="appstream" --baseurl=file:///run/media/boot/AppStream

RESULT: Local Installation Source NOT found, and no network configuration forced. The local AppStream repository pointed to the directory given in the kickstart.

**Comment by dafydd2277** [comment]
Final write up and bug: https://bugzilla.redhat.com/show_bug.cgi?id=1945779

**Comment by dafydd2277** [comment]
Even with the `network` line set, Installation Source still has problems.

- "Auto-detected installation media:" - Good, it found installation media on `sdb`.
- Additional repositories:
  - "appstream" - `file:///run/media/repo/AppStream` - This is the repo included in the kickstart file, which points to the directory on the USB flash drive, as mounted by the installer.
  - "AppStream" - `file:///run/install/mount-0000-cdrom/AppStream` - `/run/install/mount-0000-cdrom/` is an empty directory. If I deselect that one and click Done,...

the Installation Source tab still shows the "Setting up installation source..." message five minutes later, and I cannot click into that window.

**Comment by dafydd2277** [comment]
I got rid of the "appstream" repo in the kickstart file, and Installation Source built just fine. I still have a network interface activated. Of course, I have *no* idea why the `file://` repo pointing to the empty directory works, but whatever.

**Comment by dafydd2277** [comment]
This minimum `ks.cfg` works:

```
cdrom
graphical
logging --level=info
```

Adding these three items for the next test.

```
keyboard --vckeymap=us --xlayouts='us'
lang en_US.UTF-8
timezone America/Los_Angeles --isUtc
```

I'm going to work my way to adding `network` *last*, to see which point causes the installation media search to start failing.

**Comment by dafydd2277** [comment]
That still worked. Adding `services` and `%packages` next:

```
services --enabled="chronyd"
%packages
@^graphical-server-environment
@container-management
@debugging
@development
@graphical-admin-tools
@headless-management
@legacy-unix
@network-file-system-client
@performance
@remote-desktop-clients
@remote-system-management
@rpm-development-tools
@scientific
@security-tools
@system-tools
@web-server
kexec-tools
%end
```

**Comment by dafydd2277** [comment]
Adding the packages kicked off an auto-install that I had to stop. Also, prior to adding the `%packages` block, I added these in the previous test and neglected to note them:

```
xconfig  --startxonboot
eula --agreed
firstboot --enable
rootpw --iscrypted $6$cuIJ07weYTqo.yZ2$dlLm2cHoGvQd9WJzEn7O3dBOPqDpzwkT3hkl2T06jl5EasOxYaVMypJiJjERYJon7jizxg/aMAP44atXgt0y20
user --groups=wheel --name=throwaway --gecos="Test User" --iscrypted --password=$6$cuIJ07weYTqo.yZ2$dlLm2cHoGvQd9WJzEn7O3dBOPqDpzwkT3hkl2T06jl5EasOxYaVMypJiJjERYJon7jizxg/aMAP44atXgt0y20
```

With the addition of the `services` command yesterday, the *only* top line command missing is the `network` command. Which is annoying. What was causing the installer to not see the local media? I'm either going to find something in the `%addon` sections, or I'm going to have to start all over. Next up, adding these:

```
%addon com_redhat_kdump --enable --reserve-mb=auto
%end
%addon org_fedora_oscap
content-type = scap-security-guide
profile = pci-dss
%end
```

**Comment by dafydd2277** [comment]
And the `org_fedora_oscap` caused the same failure as Issue #3. So, taking that back out and adding in these:

```
%anaconda
pwpolicy root --minlen=6 --minquality=1 --notstrict --nochanges --notempty
pwpolicy user --minlen=6 --minquality=1 --notstrict --nochanges --emptyok
pwpolicy luks --minlen=6 --minquality=1 --notstrict --nochanges --notempty
%end
```

**Comment by dafydd2277** [comment]
And the most recent test worked just fine. I believe that only leaves the network line and the partitioning information. Hmph. Comparing old and new test kickstarts, now.

**Comment by dafydd2277** [comment]
Adding the disk formatting information also didn't block anything. So, putting stuff together for one more "build from minimum" test, after comparing and matching all the elements of the failed kickstart file.

**Comment by dafydd2277** [comment]
Trying the original KS file, again.

**Comment by dafydd2277** [comment]
Here's the diff of the bottom up kickstart and my current testing kickstart. This one failed.

```
[root@bravo ~]# diff ks.cfg.bottomUp ks.cfg
2d1
< #install # Deprecated
7d5
< logging --level=info
19a18,21
> # Partition clearing information
> zerombr
> ignoredisk --only-use=sda
> clearpart --initlabel --drives=sda --all
```

I'm going to comment out the `ignoredisk` and see what happens.

**Comment by dafydd2277** [comment]
This succeeds.

```
[root@bravo ~]# !diff
diff ks.cfg.bottomUp ks.cfg
2d1
< #install # Deprecated
7d5
< logging --level=info
19a18,21
> # Partition clearing information
> zerombr
> #ignoredisk --only-use=sda
> clearpart --initlabel --drives=sda --all
```

I'm going to uncomment the `ignoredisk` and add a `network` and verify that works as well.

**Comment by dafydd2277** [comment]
This succeeds.

```
[root@bravo ~]# !diff
diff ks.cfg.bottomUp ks.cfg
2d1
< #install # Deprecated
7d5
< logging --level=info
14a13
> network  --bootproto=dhcp --device=link --onboot=off --noipv6
19a19,22
> # Partition clearing information
> zerombr
> ignoredisk --only-use=sda
> clearpart --initlabel --drives=sda --all
```

**Comment by dafydd2277** [comment]
Updates added to the bug: https://bugzilla.redhat.com/show_bug.cgi?id=1945779#c4

I think I'm done at this point. I've narrowed down the issue to the combination of two commands and how they interact with each other.

**Comment by xcnix** [comment]
I got similar issue during kickstart installation of AlmaLinux 8, after reading related page from this thread, I found the root cause is the "ignoredisk" in kickstart file, this keyword will prevent anaconda to read all USB disk info during installation.

**Comment by deajan** [comment]
Just for the records, I too had problems with the missing Appstream repo on RHEL9 when using kickstart.
I tracked down the issue to being very simple:

I use a kickstart file which uses the "minimal" install template, eg:
```
text
repo --name="AppStream" --baseurl=file:///run/install/repo/AppStream

%end

[...]
# Use CDROM installation media
cdrom

%packages
@^minimal-environment
qemu-guest-agent
[...]
```

So appstream repo is never mounted on `/run/install/repo/AppStream` because I simply used the minimal installation ISO, instead of the DVD one.

Hope this helps someone ;)
